FROM openjdk:8

EXPOSE 8080

WORKDIR /usr/src/myapp

COPY ./spring-project .

RUN apt-get update && apt-get install -y maven

RUN ./mvnw package

CMD ["java","-jar","./target/docker-example-1.1.3.jar"]
