version: '3'

services:
  radis:
    image: redis:6.2.6
    volumes:
      - ./radis-cache/:/usr/local/etc/redis/
    ports:
      - 6379:6379
    networks:
      - redis-network
    container_name: redis
    command: "redis-server /usr/local/etc/redis/redis.conf"


networks:
  redis-network:
      name: redis-network
