version: '3'

services:
  logger:
    image: devopsdockeruh/simple-web-service
    volumes:
      - .:/usr/src/app/text.log
    ports:
      - 8080:8080
    container_name: docker-logger
    command: ["server"]
