version: '3'

services:
  backend:
    build: 
      context: ./backend-docker
    ports:
      - 8080
    environment:
      - VIRTUAL_HOST=backend.colasloth.com
      - REDIS_HOST=redis
      - REQUEST_ORIGIN=http://frontend.colasloth.com
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DATABASE=postgres
    depends_on: 
      - db
    container_name: backend
    #    networks:
    #      - redis-network

  frontend:
    build:
      context: ./frontend-docker
    ports:
      - 5000
    environment:
     - VIRTUAL_HOST=frontend.colasloth.com
    container_name: frontend

  redis:
    image: redis:6.2.6
    ports:
      - 6379
    container_name: redis
    environment:
      - VIRTUAL_HOST=redis.colasloth.com
    volumes:
      - ./redis/conf/:/usr/local/etc/redis/
      - ./redis:/var/lib/redis
    command: "redis-server /usr/local/etc/redis/redis.conf"
  
  hello:
    image: nginx:alpine
    volumes:
      - ./proxy/hello.html:/usr/share/nginx/html/index.html:ro
    environment:
      - VIRTUAL_HOST=hello.colasloth.com
    container_name: hello

  world:
    image: nginx:alpine
    volumes:
      - ./proxy/world.html:/usr/share/nginx/html/index.html:ro
    environment:
      - VIRTUAL_HOST=world.colasloth.com
    container_name: world

  db:
    image: postgres:13.2-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
    container_name: db

  proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
    container_name: proxy
