version: '3'

services:
  backend:
    build: 
      context: ./backend-docker
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DATABASE=postgres
    container_name: backend

  frontend:
    build:
      context: ./frontend-docker
    ports:
      - 5002:5000
    container_name: frontend

  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_PASSWORD: example
    restart: unless-stopped
    container_name: db

  adminer:
    image: adminer:4
    ports:
      - 8088:8080
    container_name: adminer

volumes:
  database:
