version: '3'

services:
  backend:
    build: 
    # dockerfile: Dockerfile
      context: ./backend-docker
    ports:
      - 8080:8080
    container_name: backend

  frontend:
    build:
    # dockerfile: Dockerfile
      context: ./frontend-docker
    ports:
      - 5002:5000
    container_name: frontend
